### ISSUE TITLE
Fix Bookmark Ajax button to work without refreshing

### ISSUE THREAD

**Issue by ribaishtiaq** [ribaishtiaq/Adzwall#12]
Fix the bookmark ajax button to work without refreshing the page after every click,

**Comment by avinashupadhya99** [comment]
Hey, I can help with this. You can assign this to me.

**Comment by ribaishtiaq** [comment]
thanks, Sure :)

**Comment by ribaishtiaq** [comment]
fixed in 7ed7465eb197ddd35b76ad55f3167189fda67e02

**Comment by ribaishtiaq** [comment]
fixed
